<template>
  <div>
    <ChannelHeader :routeName="this.$route.name" />
    <div class="container px-md-0 px-4">
      <button
        type="button"
        class="btn btn-orange btn-sm ml-auto"
        @click.prevent="isSearch = !isSearch"
      >
        <font-awesome-icon :icon="['fas', 'search']" />
      </button>
      <div
        v-if="isSearch"
        class="card card-flat card-body bg-dark border border-neon-yellow"
        :class="isSearch ? 'fade-in-top' : 'fade-out-top'"
      >
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text px-3" id="basic-addon1"
              ><font-awesome-icon :icon="['fas', 'search']" size="lg"
            /></span>
          </div>
          <input
            type="text"
            class="form-control form-control-lg form-dark bg-transparent text-light"
            placeholder="Pesquisar aqui"
          />
        </div>
      </div>
    </div>

    <div class="container mb-4 px-md-0 px-4">
      <h2 class="mt-3">
        <span
          class="marker marker-title"
          :class="isDarkMode ? 'marker-light' : 'marker-dark'"
        >
          <strong> Artigos recentes </strong>
        </span>
      </h2>
      <div class="row">
        <div
          v-for="(article, i) in articles"
          :key="i"
          class="col-lg-4 col-md-6 col-12"
        >
          <Cards :article="article" :isFlat="true" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Cards from "~/components/Cards";
import ChannelHeader from "~/components/ChannelHeader";
export default {
  components: { Cards, ChannelHeader },

  async asyncData({ $content, params }) {
    const articles = await $content("nerdstation", params.slug)
      .only(["title", "img", "imgAlt", "dir", "channel", "slug", "createdAt"])
      .sortBy("createdAt", "desc")
      .where({ channel: "nerdstation" })
      .fetch();

    return {
      articles,
    };
  },
  data() {
    return {
      isSearch: false,
    };
  },

  // methods: {
  //   showSearch() {
  //     isSearch
  //   },
  // },
};
</script>
<style lang="scss">
.fade-in-top {
  -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
.fade-out-top {
  -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.fade-in-left {
  -webkit-animation: fade-in-left 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-left 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-11-30 17:30:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-in-left
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-left {
  0% {
    -webkit-transform: translateX(-50px);
    transform: translateX(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes fade-in-left {
  0% {
    -webkit-transform: translateX(-50px);
    transform: translateX(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
}
@keyframes fade-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
}
</style>
