<template>
  <div
    class="d-flex flex-column h-100"
    :class="isDarkMode ? 'bg-dark' : 'bg-polen'"
  >
    <Navbar />
    <Nuxt />
    <ImageFilter />
    <Footer />
  </div>
</template>
<script>
import { mapGetters } from "vuex";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ImageFilter from "@/components/ImageFilter";

export default {
  components: { Navbar, Footer, ImageFilter },
  computed: {
    ...mapGetters(["isDarkMode"]),
  },
};
</script>

<style>
@import "~/assets/style/css/ultimate.css";
</style>
<style lang="scss">
// .slide-in-left-enter-active {
//   -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
//     both;
//   animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
// }
// .slide-in-left-leave-active {
//   -webkit-animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
//     both;
//   animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
// }

// .slide-in-left-enter,
// .slide-in-left-leave-to {
//   -webkit-animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
//     both;
//   animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
// }

// .slide-in-left {
//   -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
//     both;
//   animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
// }
// .slide-in-right {
//   -webkit-animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
//     both;
//   animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
// }
/* ----------------------------------------------
 * Generated by Animista on 2020-12-7 17:32:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

.hover-card {
  &-uv,
  &-yellow {
    .card-img-border {
      border-radius: 0.5rem;
    }
  }

  &-uv,
  &-yellow {
    &:hover {
      .card-img-border {
        // transition: ease-in 0.1s;
        border-radius: 0 !important;
      }
    }
  }
}
</style>
